remote_theme: akademie-oeffentliches-gesundheitswesen/lehrbuch-theme

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

title: Lehrbuch Gutachten im ÖGD

github: [metadata]

# Aux links for the upper right navigation
aux_links:
  "Lehrbuch auf GitHub":
    - ""
    
logo: "akademie.jpeg"
